FROM debian

MAINTAINER llachgar <llachgar@student.1337.ma>


EXPOSE 9987/udp 10011 30033

RUN	apt-get update && apt-get upgrade -y && \
	apt-get install -y wget bzip2 && \
	wget http://dl.4players.de/ts/releases/3.5.0/teamspeak3-server_linux_amd64-3.5.0.tar.bz2 && \
	tar -xvf  teamspeak3-server_linux_amd64-3.5.0.tar.bz2 

WORKDIR teamspeak3-server_linux_amd64

ENTRYPOINT sh ts3server_minimal_runscript.sh

# to build docker build -t ex01 .
# to run docker run --rm -p 9987:9987/udp -p 10011:10011 -p 30033:30033 --env TS3SERVER_LICENSE=accept ex01

